# Generated by Django 3.1.5 on 2021-01-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('excerpt', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('place', models.CharField(max_length=30)),
                ('headline', models.CharField(max_length=100)),
            ],
        ),
    ]
